services:
  database:
    image: "postgres:16.2-alpine3.19"
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - backend-network

  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - frontend-network

  backend:
    build: "./backend"
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: on-failure
    networks:
      - backend-network
      - frontend-network
    env_file:
      - .env

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
